# Generated by Django 5.0.7 on 2025-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='status',
            field=models.CharField(choices=[('healthy', 'ปกติ'), ('sick', 'ป่วย'), ('forsale', 'พร้อมขาย')], default='healthy', max_length=20),
        ),
    ]
