# Generated by Django 5.0.7 on 2025-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_healthcheck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
