# Generated by Django 5.0.7 on 2025-09-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_cattle_for_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('feeding', 'การให้อาหาร'), ('health', 'การรักษา'), ('breeding', 'ผสมพันธุ์'), ('other', 'อื่นๆ')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cattle.cattle')),
            ],
        ),
    ]
