# Generated by Django 5.0.7 on 2025-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='for_sale',
        ),
        migrations.AddField(
            model_name='cattle',
            name='status',
            field=models.CharField(choices=[('healthy', 'ปกติ'), ('sick', 'ป่วย'), ('forsale', 'พร้อมขาย')], default='healthy', max_length=20),
        ),
    ]
