# Generated by Django 5.0.7 on 2025-09-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0005_remove_cattle_for_sale_cattle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='status',
        ),
    ]
