# Generated by Django 5.0.7 on 2025-09-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0006_remove_cattle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='housing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gender',
            field=models.CharField(choices=[('male', 'ตัวผู้'), ('female', 'ตัวเมีย')], max_length=10),
        ),
        migrations.CreateModel(
            name='FeedingRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration_id', models.CharField(max_length=50)),
                ('feeding_time', models.CharField(max_length=100)),
                ('fresh_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dry_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplement', models.TextField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rations', to='cattle.cattle')),
            ],
        ),
    ]
