# Generated by Django 5.0.7 on 2025-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0007_cattle_category_cattle_housing_alter_cattle_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='feeding_rations',
            field=models.TextField(blank=True, null=True, verbose_name='การให้อาหาร'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='treatments',
            field=models.TextField(blank=True, null=True, verbose_name='การรักษา/ยา'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='vaccinations',
            field=models.TextField(blank=True, null=True, verbose_name='วัคซีน'),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
