# Generated by Django 5.0.7 on 2025-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0008_healthcheck_feeding_rations_healthcheck_treatments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheck',
            name='feeding_rations',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='treatments',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='vaccinations',
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='feeding_rations',
            field=models.ManyToManyField(blank=True, to='cattle.feedingration'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='treatments',
            field=models.ManyToManyField(blank=True, to='cattle.treatment'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, to='cattle.vaccination'),
        ),
    ]
