# Generated by Django 5.0.7 on 2025-09-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0009_remove_healthcheck_feeding_rations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheck',
            name='feeding_rations',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='treatments',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='vaccinations',
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='status',
            field=models.CharField(choices=[('healthy', 'ปกติ'), ('sick', 'ป่วย'), ('forsale', 'พร้อมขาย')], default='healthy', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
