# Generated by Django 5.0.7 on 2025-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0010_remove_healthcheck_feeding_rations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='father',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='mother',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
